config/routes.rb
Rails.application.routes.draw do
  resources :moderate_tasks
  devise_for :users
  resources :users, only: [:show, :index]
  
  #get 'tags/index'

  get 'posts/autocomplete'
  #get 'panel/index'
  #resources :panel, only: [:index, :posts]

  #get '/panel', to: 'panel#index'
  #get '/panel/posts', to: 'panel#posts'

  resources :posts do
  	resources :comments
	end


  resources :tags 
  resources :tag_aliases
  resources :pools

  root "posts#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match '/users/:id', to: 'users#show', via: 'get'
  match "*path", to: "application#catch_404", via: :all
end

app/models/pool.rb
class Pool < ApplicationRecord
  has_and_belongs_to_many :posts
  belongs_to :user
  validates :name, presence: true, uniqueness: true

  def posts_string
    self.post_ids.to_s.gsub(/[,\[\]]/,"")
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  def index
    @pools = Pool.page(params[:page]).per(12)
  end

  def show
    @posts = @pool.posts.page params[:page]
  end

  def new
    @pool = Pool.new
  end

  def create
    @pool = Pool.create(name: pool_params[:name])
    @pool.user = cureent_user
    pool_params[:posts_string].split(" ").each do |post_id|
      next unless Post.exists?(post_id)
      post = Post.find(post_id)
      @pool.posts << post
    end
    redirect_to pool_url(@pool)
  end

  def update

  end

  def destroy
    @pool.destroy
    redirect_to pools_url
  end

  private
  def pool_params
    params.require(:pool).permit(:name, :posts_string)
  end

  def set_pool
    @pool = Pool.find(params[:id])
  end
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.slim
= simple_form_for pool do |form|
	= form.input :name
	= form.label "Посты"
	= form.text_area :posts_string, class: "form-control"
	= form.submit class: "btn btn-primary mb-2"

app/views/pools/_nav_bar.html.slim
= link_to "Добавить пул", new_pool_path, class: "nav-link"
- if action_name == "show"
  - if can? :update, @pool
    li.nav-item
      = link_to "Изменить", edit_pool_path(@pool), class: "nav-link"
  - if can? :destroy, @pool
    li.nav-item
      = link_to "Удалить", pool_path(@pool), class: "nav-link", method: :delete

app/views/pools/edit.html.slim
= render 'form', pool: @pool

app/views/pools/index.html.slim
.container-fluid
  .row
    table.table
      thead.thead-light
        tr
          th scope="col"  Name
          th scope="col" Count
          th
      tbody
        - @pools.each do |pool|
          tr
            td= link_to pool.name, pool_url(pool)
            td= pool.posts.count
            td

app/views/pools/new.html.slim
= render 'form', pool: @pool

app/views/pools/show.html.slim
h4 | Name: #{@pool.name} | Creator: #{@pool.user.username}
.row.mx-auto#posts
	= render @posts
	= paginate @posts