config/routes.rb
Rails.application.routes.draw do
  resources :moderate_tasks
  devise_for :users
  resources :users, only: [:show, :index]
  
  #get 'tags/index'

  get 'posts/autocomplete'
  #get 'panel/index'
  #resources :panel, only: [:index, :posts]

  #get '/panel', to: 'panel#index'
  #get '/panel/posts', to: 'panel#posts'

  resources :posts do
  	resources :comments
	end


  resources :tags 
  resources :tag_aliases
  resources :pools

  root "posts#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match '/users/:id', to: 'users#show', via: 'get'
  match "*path", to: "application#catch_404", via: :all
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :name, presence: true
	validates :name, uniqueness: true

	has_and_belongs_to_many :posts

  has_many :tag_aliases
  has_many :aliases, through: :tag_aliases
  has_many :inverse_tag_aliases, class_name: "TagAlias", foreign_key: "alias_id"
  has_many :inverse_aliases, through: :inverse_tag_aliases, source: :tag
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_tag, only: [:show, :edit, :destroy, :update]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_tag

  def index
    @tags = Tag.all.order(:id).reverse_order.page(params[:page]).per(12)
  end

  def show
    redirect_to posts_url(tags: @tag.name)
  end

  def new
    @tag = Tag.new
  end

  def create
    #@tag = Tag.new(name: params[:tag][:name].downcase)
    tag_service = TagService.new
    tag_service.create_new_tags(params[:tag][:name])
    redirect_to tags_url
    #respond_to do |format|
    #  if tag_service.save? #@tag.save
    #    format.html {redirect_to tags_url}
    #  else
    #    format.html {redirect_to tags_url notide: "wrong argiments"}
    #  end
    #end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html {redirect_to tags_url}
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html {redirect_to tags_index_url}
      else
        format.html {redirect_to tags_index_url notide: "wrong argiments"}
      end
    end
  end

  private

    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end

    def invalid_tag
      redirect_to tags_index_url
    end

end

app/helpers/tags_helper.rb
module TagsHelper

end

app/views/tags/_form.html.slim
= simple_form_for tag do |f|
  = f.label "Теги"
  = f.text_area :name, class: "form-control"
  = f.hint 'Разделяйте теги пробелом.'
  = f.button :submit

app/views/tags/_list.html.slim
div.card
	div.card-block
		h4.card-title Теги
		ul
			-@tags.each do |t|
				li.tag_li
					= link_to t.name, posts_url(tags: t.name), class: "tag-link"
					span.badge.badge-dark = t.posts_count
					a href="javascript:;"
						span.badge.bg-secondary.add_button +

app/views/tags/_nav_bar.html.slim
-if can? :create, Tag
	li.nav-item
	= link_to "Добавить", new_tag_path, class: "nav-link" 

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<%= render 'form', tag: @tag %>

app/views/tags/index.html.slim
.container-fluid
  .row
    table.table
      thead.thead-light
        tr
          th scope="col"  Id
          th scope="col"  Images
          th scope="col"  Name
          th scope="col" 
          th scope="col" 
          th scope="col" 
          th scope="col" 
      tbody
        - @tags.each do |tag|
          tr
            td= tag.id
            td= tag.posts_count
            td= link_to tag.name, posts_url(tags: tag.name)
            td= link_to "change", edit_tag_path(tag)
            td= link_to "delete", tag, method: :delete
            td
            td
    = paginate @tags

app/views/tags/new.html.slim
.row
	.col-lg-2
	.col-lg-8
		= render "form", tag: @tag
	.col-lg-2

app/views/tags/show.html.erb
All images with tag: <%= @tag.name %>
<br />
Count: <%= @posts.count %>
<br />
<% @posts.each do |post|%>
	<%= link_to (image_tag post.image.thumb), post_path(post) %>
<% end %>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>