config/routes.rb
Rails.application.routes.draw do
  resources :moderate_tasks
  devise_for :users
  resources :users, only: [:show, :index]
  
  #get 'tags/index'

  get 'posts/autocomplete'
  #get 'panel/index'
  #resources :panel, only: [:index, :posts]

  #get '/panel', to: 'panel#index'
  #get '/panel/posts', to: 'panel#posts'

  resources :posts do
  	resources :comments
	end


  resources :tags 
  resources :tag_aliases
  resources :pools

  root "posts#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match '/users/:id', to: 'users#show', via: 'get'
  match "*path", to: "application#catch_404", via: :all
end

app/models/moderate_task.rb
class ModerateTask < ApplicationRecord
  enum task_type: [:creation, :deletion, :edition]
  enum model_type: [:post, :pool, :tag_alias]
  enum status: [:open, :close]
  
  belongs_to :creator, class_name: 'User'
  belongs_to :passer, class_name: 'User', optional: true

  validates :passer, presence: false
end

app/controllers/moderate_tasks_controller.rb
class ModerateTasksController < ApplicationController
  #before_action :set_moderate_task, only: [:show, :edit, :update, :destroy]

  # GET /moderate_tasks
  # GET /moderate_tasks.json
  def index
    @moderate_tasks = ModerateTask.order(:created_at).reverse_order.page params[:page]
  end

  # GET /moderate_tasks/1
  # GET /moderate_tasks/1.json
  def show
  end

  # GET /moderate_tasks/new
  def new
    @moderate_task = ModerateTask.new
  end

  # GET /moderate_tasks/1/edit
  def edit
  end

  # POST /moderate_tasks
  # POST /moderate_tasks.json
  def create
    puts params
    if params[:tasks].any?
      #ModTaskService.close(params[:tasks],current_user)
    else
      #ModTaskService.close(params[:id],current_user)
      #@moderate_task = ModerateTask.find(params[:id])
    end
    #@moderate_task = ModerateTask.new(moderate_task_params)

    #respond_to do |format|
    #  if @moderate_task.save
    #    format.html { redirect_to @moderate_task, notice: 'Moderate task was successfully created.' }
    #    format.json { render :show, status: :created, location: @moderate_task }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @moderate_task.errors, status: :unprocessable_entity }
    #  end
    #end

  end

  # PATCH/PUT /moderate_tasks/1
  # PATCH/PUT /moderate_tasks/1.json
  def update
    ModTaskService.close(params[:tasks],current_user)
    #ModTaskService.close(params[:tasks],current_user)
    #respond_to do |format|
    #  if @moderate_task.update(moderate_task_params)
    #    format.html { redirect_to @moderate_task, notice: 'Moderate task was successfully updated.' }
    #    format.json { render :show, status: :ok, location: @moderate_task }
    #  else
    #    format.html { render :edit }
    #    format.json { render json: @moderate_task.errors, status: :unprocessable_entity }
    #  end
    #end
    redirect_to moderate_tasks_url, notice: ':ok'
  end

  # DELETE /moderate_tasks/1
  # DELETE /moderate_tasks/1.json
  def destroy
    @moderate_task.destroy
    respond_to do |format|
      format.html { redirect_to moderate_tasks_url, notice: 'Moderate task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moderate_task
      @moderate_task = ModerateTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moderate_task_params
      params.require(:moderate_task).permit(:type, :model_type, :model_id, :creator, :passer)
    end
end

app/helpers/moderate_tasks_helper.rb
module ModerateTasksHelper
end

app/views/moderate_tasks/_form.html.slim
= simple_form_for(@moderate_task) do |f|
  = f.error_notification

  .form-inputs
    = f.input :task_type
    = f.input :model_type
    = f.input :model_id
    = f.input :creator
    = f.input :passer

  .form-actions
    = f.button :submit

app/views/moderate_tasks/_nav_bar.html.slim
= link_to "Посты", moderate_tasks_url, class: "nav-link"
= link_to "Синонимы", "", class: "nav-link"
= link_to "Пулы", "", class: "nav-link"

app/views/moderate_tasks/edit.html.slim
h1 Editing moderate_task

== render 'form'

=> link_to 'Show', @moderate_task
'|
=< link_to 'Back', moderate_tasks_path

app/views/moderate_tasks/index.html.slim
h1 Список тасков на модерацию
= form_tag "/moderate_tasks/1", method: :put do
  .row
    .col-md-12
      = submit_tag "Принять", class: "btn btn-default btn-block"
  br
  - @moderate_tasks.each do |moderate_task|
    .row
      .col-md-12
        .card
          .card-body
            .row
              .col-md-1
                = check_box_tag 'tasks[]', moderate_task.id
              .col-md-1
                | #{moderate_task.status}
              .col-md-2
                | Тип: #{moderate_task.task_type}
                br
                | Модель: #{moderate_task.model_type}
              .col-md-2
                | ИД модели: #{moderate_task.model_id}
              .col-md-2
                | Польз.: #{moderate_task.creator.username}
              .col-md-2
                | Дата: #{moderate_task.created_at.strftime("%H:%M %d/%m/%Y")}
              .col-md-1
                = link_to "Cсылка", post_url(id: moderate_task.model_id) 
= paginate @moderate_tasks

app/views/moderate_tasks/new.html.slim
h1 New moderate_task

== render 'form'

= link_to 'Back', moderate_tasks_path

app/views/moderate_tasks/show.html.slim
p#notice = notice

p
  strong Task Type:
  = @moderate_task.task_type
p
  strong Model type:
  = @moderate_task.model_type
p
  strong Model:
  = @moderate_task.model_id
p
  strong Creator:
  = @moderate_task.creator
p
  strong Passer:
  = @moderate_task.passer

=> link_to 'Edit', edit_moderate_task_path(@moderate_task)
'|
=< link_to 'Back', moderate_tasks_path