config/routes.rb
Rails.application.routes.draw do
  resources :moderate_tasks
  devise_for :users
  resources :users, only: [:show, :index]
  
  #get 'tags/index'

  get 'posts/autocomplete'
  #get 'panel/index'
  #resources :panel, only: [:index, :posts]

  #get '/panel', to: 'panel#index'
  #get '/panel/posts', to: 'panel#posts'

  resources :posts do
  	resources :comments
	end


  resources :tags 
  resources :tag_aliases
  resources :pools

  root "posts#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match '/users/:id', to: 'users#show', via: 'get'
  match "*path", to: "application#catch_404", via: :all
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #user ||= User.new # guest user (not logged in)
    if user.nil?
      can :read, [Post, Tag, Comment, Pool, TagAlias]
    elsif user.admin_role?
      can :manage, :all
    else
      can [:read, :create], [Post, Tag, Comment]
      can [:destroy], Post, user_id: user.id
      can [:update], Post
      can [:destroy], Comment, user_id: user.id
      can [:read], User, id: user.id
      can [:read, :create], Pool
      can [:update], Pool, user_id: user.id
      can [:read], TagAlias
      cannot [:manage], ModerateTask
      #can :manage, []
    end

    #if user.admin_role?
    #  can :manage, :all
    #else
    #  can :read, [:posts, :tags]
    #end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	
	validates :body, presence: true
end

app/models/moderate_task.rb
class ModerateTask < ApplicationRecord
  enum task_type: [:creation, :deletion, :edition]
  enum model_type: [:post, :pool, :tag_alias]
  enum status: [:open, :close]
  
  belongs_to :creator, class_name: 'User'
  belongs_to :passer, class_name: 'User', optional: true

  validates :passer, presence: false
end

app/models/pool.rb
class Pool < ApplicationRecord
  has_and_belongs_to_many :posts
  belongs_to :user
  validates :name, presence: true, uniqueness: true

  def posts_string
    self.post_ids.to_s.gsub(/[,\[\]]/,"")
  end
end

app/models/post.rb
class Post < ApplicationRecord
  enum rating: [:safe, :nsfw, :questionable]
  enum status: [:pending, :published]

	has_and_belongs_to_many :tags, counter_cache: true
  has_and_belongs_to_many :pools
  
	has_many :comments, dependent: :destroy
  belongs_to :user

  validates :md5, uniqueness: true

	#accept_nested_attributes_for :comments

	mount_uploader :image, ImageUploader
  validates_presence_of :image
  validates_processing_of :image
  validates :image, file_size: {less_than: 5.megabytes}

  def tags_string
    self.tags.map(&:name).join(" ")
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :name, presence: true
	validates :name, uniqueness: true

	has_and_belongs_to_many :posts

  has_many :tag_aliases
  has_many :aliases, through: :tag_aliases
  has_many :inverse_tag_aliases, class_name: "TagAlias", foreign_key: "alias_id"
  has_many :inverse_aliases, through: :inverse_tag_aliases, source: :tag
end

app/models/tag_alias.rb
class TagAlias < ApplicationRecord
  validates :tag_id, presence: true
  validates :alias_id, presence: true

  belongs_to :tag
  belongs_to :alias, class_name: "Tag"
  #belongs_to :tag, class_name: "Tag"
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :posts
  has_many :pools
  #has_many :created_moderate_tasks, class_name: 'ModerateTask', foreign_key: 'creator_id'
  #has_many :passsed_moderate_tasks, class_name: 'ModerateTask', foreign_key: 'passer_id'

  attr_accessor :login

  def login=(login)
  	@login = login
  end

  def login
  	@login || self.username #|| self.email
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_tag, only: [:show, :edit, :destroy, :update]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_tag

  def index
    @tags = Tag.all.order(:id).reverse_order.page(params[:page]).per(12)
  end

  def show
    redirect_to posts_url(tags: @tag.name)
  end

  def new
    @tag = Tag.new
  end

  def create
    #@tag = Tag.new(name: params[:tag][:name].downcase)
    tag_service = TagService.new
    tag_service.create_new_tags(params[:tag][:name])
    redirect_to tags_url
    #respond_to do |format|
    #  if tag_service.save? #@tag.save
    #    format.html {redirect_to tags_url}
    #  else
    #    format.html {redirect_to tags_url notide: "wrong argiments"}
    #  end
    #end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html {redirect_to tags_url}
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html {redirect_to tags_index_url}
      else
        format.html {redirect_to tags_index_url notide: "wrong argiments"}
      end
    end
  end

  private

    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end

    def invalid_tag
      redirect_to tags_index_url
    end

end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def second_nav_bar_for(controller_name)
    synonyms = {
      "sessions" => "users",
      "passwords" => "users",
      "registrations" => "users"
    }
    new_name = synonyms.has_key?(controller_name) ? synonyms[controller_name] : controller_name
    return "#{new_name}/nav_bar"
  end
  
  def active_link_for(controller, button_name)
    
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper

end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_string_for(post)
    post.tags.map{|t| t.name}.join(" ")
  end

  def link_to_image(post)
    post.samp ? post.image.sample : post.image
  end
end

app/helpers/tag_aliase_helper.rb
module TagAliaseHelper
end

app/helpers/tags_helper.rb
module TagsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_guest.html.slim
li.nav-item
  = link_to "Регистрация", new_user_registration_path, class: "nav-link"
li.nav-item
  = link_to "Войти", new_user_session_path, class: "nav-link"

app/views/layouts/_nav_bar.html.slim
nav.navbar.navbar-toggleable-md.navbar-inverse.bg-inverse
  button.navbar-toggler.navbar-toggler-right aria-controls="navbarCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarCollapse" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  = link_to "Railbooru", root_url, class: "navbar-brand"
  #navbarCollapse.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        = link_to "Посты", posts_url, class: "nav-link"
      li.nav-item
        = link_to "Теги", tags_path, class: "nav-link"
      li.nav-item
        = link_to "Синонимы", tag_aliases_path, class: "nav-link"
      li.nav-item
        = link_to "Пулы", pools_path, class: "nav-link"
      - if user_signed_in?
        li.nav-item
          = link_to "Аккаунт", user_url(current_user), class: 'nav-link'
        - if current_user.admin_role?
          li.nav-item
            = link_to "Панель администратора", moderate_tasks_url, class: 'nav-link'          

nav.navbar.navbar-toggleable-md.navbar-inverse.navbar-inverse style=("background-color: #536379;") 
  ul.navbar-nav.mr-auto
    - if user_signed_in?
      = render second_nav_bar_for(controller_name)
    - else
      = render "layouts/guest"


    

app/views/layouts/_search_form.html.slim
.form-group.row
  .col-sm-12
    = form_tag(posts_path, method: :get) do
      = submit_tag "Искать", class: "btn btn-primary btn-sm btn-block", id:"search_button"
      datalist#autocomp
      = search_field_tag :tags, nil, class: "form-control form-control-sm", id: "searchForm", list: "autocomp", autocomplete: "off"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Railbooru
    = csrf_meta_tags
    = favicon_link_tag "logo.ico"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://v4-alpha.getbootstrap.com/dist/css/bootstrap.css" rel="stylesheet" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
  body
    = render 'layouts/nav_bar'
    .container-fluid.pt-4
      - if notice
        p.alert.alert-success= notice
      - if alert
        p.alert.alert-danger= alert
      = yield
    footer.footer.bg-light
      .container
        span.text-dark